### ISSUE TITLE
Unipi DeviceClass not available after update from version 0.1 to 0.3.1 "Buffer.alloc is not a function"

### ISSUE THREAD

**Issue by emeins** [mwittig/pimatic-unipi-evok#25]
I would like to share an issue I had when I updated from version 0.1 to 0.3.1. I also updated the evok version from 1.0 to 2.0 (1.0 seems not to work with pimatic-unipi-evok 0.3.x). After updating pimatic-unipi-evok to 0.3.1 no UniPi device class was available in pimatic anymore, exiting devices were not able to be managed.
The pimatic-daemon.log throw an error "Buffer.alloc is not a function" which seems to be connected to the Node version <4.5. Compare https://github.com/lovell/sharp/issues/847
After updating to 4.8.3 as it it recommended in the Pimatic installation guide everything worked well.
Maybe an update of the installation dependencies of this plugin would help. Put there are already some movements in pimatic to go forward with more current node versions...

**Comment by mwittig** [comment]
Thanks for the info. I'll take this info for a trouble shooting section.
